### ISSUE TITLE
Annotate which Rust and ink! version was used

### ISSUE THREAD

**Issue by Robbepop** [Stefie/substrate-ink-compiled-examples#1]
Since ink! and Rust Wasm output might be changing a lot from version to version we might want to annotate the current state of the compiled smart contracts and their associated ABI files.

**Comment by Stefie** [comment]
Yeah, I was thinking about that, too! I can just create folders matching different ink! versions.
This repo was mainly for people woking with the FE implementation of the `srml/contracts` module to have easy access to compiled WASM code + ABI of different example contracts.

**Comment by Robbepop** [comment]
Alternatively you can use tags so that people can just jump to them via `git`. Whatever you think is best.

**Comment by Stefie** [comment]
You're not using any tags or releases in ink! yet. But having tags that I can reference to would be even nicer than just manual folders. 
 As for this repo tags would be an overload and not very practical. Being able to check out different versions of the WASM files at once is what's needed. We need different files & versions for testing to see what breaks things.

**Comment by Robbepop** [comment]
> Being able to check out different versions of the WASM files at once is what's needed. We need different files & versions for testing to see what breaks things.

Ah good point!
